"""Emit the proven recognizer metadata as a generated C header for the firmware.

This is the Phase-0 bridge to the marvin `gameplay_engine` port (spec §4.8): the
algorithms are proven host-side here, and their *data* — the screen-classifier
centroids/thresholds, the static-list menu geometry + per-cell baselines, and the
song-select templates/ROIs — is frozen into a single header the firmware compiles
in. The C code (Phase 1+) is written separately; this only produces the tables.

Layout is plain PODs + flat arrays so the firmware can consume it directly:
- screen classifier: `gp_fp_config`, `gp_screen_ids[]`, `gp_centroids[][]`, thresholds.
- static-list reader: `gp_menus[]` (geometry) + per-menu item-id and baseline arrays.
- song reader: `gp_song_*` config/ROIs + `gp_song_templates[]` + per-song vec arrays.

Floats are the per-frame-normalized baselines/song vectors (soft-float on the
ARM926, over small vectors — see the journal's port decision). `uint8` centroids
and integer thresholds/ROIs are exact.
"""

from __future__ import annotations

import numpy as np

from .classifier import build_templates
from .corpus import Sample, load_corpus, load_score_corpus
from .evaluate import labelled_fps, recommend_thresholds
from .fingerprint import CANONICAL_H, CANONICAL_W, FingerprintConfig
from .highlight import build_selection_calibration
from .corpus import load_streak_corpus
from .metadata import (
    HORIZONTAL,
    MENU_LAYOUTS,
    SCORE_DIGIT_BAND,
    SCORE_MULT_BRIGHT_MIN,
    SCORE_MULT_MIN_COUNT,
    SCORE_MULT_ROI,
    SCORE_MULT_SAT_MIN,
    SETLIST_BG_ROI,
    SONG_FIRST_ROI,
    SONG_SLOT_ROI,
    STREAK_DEBOUNCE,
    STREAK_MAX_STEP,
    STREAK_NOTE_CELL,
    STREAK_NOTE_MAX_SAD,
    STREAK_UNK_DIST,
    STREAK_UNK_MARGIN,
)
from .score import (
    DEFAULT_SCORE_CONFIG,
    DEFAULT_STREAK_CONFIG,
    STREAK_CELLS,
    build_score_catalog,
    build_streak_catalog,
)
from .songselect import DEFAULT_SONG_CONFIG, FIRST, build_song_catalog

# Score modes emitted, in device-index order (GP_SCORE_MODE_*). Career (green
# font) appends here once it has a labelled corpus + digit band — no API change.
_SCORE_MODES = ("training",)


def _c_ident(name: str) -> str:
    return name.replace("-", "_")


def _u8_rows(arr: np.ndarray, indent: str = "  ") -> str:
    return ",\n".join(
        indent + "{" + ",".join(str(int(v)) for v in row) + "}" for row in arr
    )


def _floats(vec) -> str:
    return ",".join(f"{float(v):.6g}f" for v in vec)


def build_metadata_header(samples: list[Sample] | None = None) -> str:
    if samples is None:
        samples = load_corpus()

    cfg = FingerprintConfig()
    templates = build_templates(labelled_fps(samples, cfg), cfg)
    rec = recommend_thresholds(samples, cfg)
    calib = build_selection_calibration(samples)
    catalog = build_song_catalog(samples)
    song_cfg = DEFAULT_SONG_CONFIG
    song_len = song_cfg.cols * song_cfg.rows

    screen_index = {sid: i for i, sid in enumerate(templates.ids)}
    L: list[str] = []
    w = L.append

    w("/* Generated by `gameplay export-c` — do not edit by hand.")
    w("   Recognizer metadata for the marvin gameplay_engine (spec §4.8). */")
    w("#ifndef GAMEPLAY_METADATA_H")
    w("#define GAMEPLAY_METADATA_H")
    w("#include <stdint.h>")
    w("")
    w("#define GP_CANON_W %d" % CANONICAL_W)
    w("#define GP_CANON_H %d" % CANONICAL_H)
    w("#define GP_SCREEN_UNKNOWN 0xFFu")
    w("")

    # ── screen classifier ──────────────────────────────────────────────────
    w("/* ── screen classifier (fixed-region fingerprint, nearest centroid) ── */")
    w("#define GP_FP_COLS %d" % cfg.cols)
    w("#define GP_FP_ROWS %d" % cfg.rows)
    w("#define GP_FP_SAMPLES %d  /* N×N lattice per region; 0 = dense */"
      % (cfg.samples_per_region or 0))
    w("#define GP_FP_NORMALIZE %d" % int(cfg.normalize))
    w("#define GP_FP_LEN %d" % cfg.length)
    w("#define GP_N_SCREENS %d" % len(templates.ids))
    w("#define GP_CLS_T_ABS %d" % rec.rec_t_abs)
    w("#define GP_CLS_T_MARGIN %d" % rec.rec_t_margin)
    w("")
    for i, sid in enumerate(templates.ids):
        w("#define GP_SCREEN_%s %d" % (_c_ident(sid), i))
    w("")
    w("static const char *const gp_screen_ids[GP_N_SCREENS] = {")
    w("  " + ", ".join('"%s"' % sid for sid in templates.ids))
    w("};")
    w("static const uint8_t gp_centroids[GP_N_SCREENS][GP_FP_LEN] = {")
    w(_u8_rows(templates.centroids))
    w("};")
    w("")

    # ── static-list highlight reader ───────────────────────────────────────
    w("/* ── static-list selection reader (per-cell deviation from baseline) ── */")
    menu_ids = [sid for sid in MENU_LAYOUTS if sid in calib.baselines]
    w("#define GP_N_MENUS %d" % len(menu_ids))
    w("#define GP_AXIS_V 0")
    w("#define GP_AXIS_H 1")
    for sid in menu_ids:
        lay = MENU_LAYOUTS[sid]
        ident = _c_ident(sid)
        w('static const char *const gp_menu_%s_items[%d] = {%s};'
          % (ident, lay.count, ", ".join('"%s"' % it for it in lay.items)))
        base = calib.baselines[sid].reshape(-1)
        w("static const float gp_menu_%s_baseline[%d] = {%s};"
          % (ident, base.size, _floats(base)))
    w("")
    w("typedef struct {")
    w("  uint8_t screen;            /* index into gp_screen_ids */")
    w("  uint8_t axis;              /* GP_AXIS_V | GP_AXIS_H */")
    w("  uint8_t count;             /* cells / items */")
    w("  uint16_t band[4];          /* x0, y0, x1, y1 (canonical space) */")
    w("  const char *const *items;  /* count item ids */")
    w("  const float *baseline;     /* count*3 per-cell BGR (normalized space) */")
    w("} gp_menu_layout_t;")
    w("static const gp_menu_layout_t gp_menus[GP_N_MENUS] = {")
    for sid in menu_ids:
        lay = MENU_LAYOUTS[sid]
        ident = _c_ident(sid)
        axis = "GP_AXIS_H" if lay.axis == HORIZONTAL else "GP_AXIS_V"
        b = lay.band
        w("  {GP_SCREEN_%s, %s, %d, {%d,%d,%d,%d}, gp_menu_%s_items, gp_menu_%s_baseline},"
          % (ident, axis, lay.count, b[0], b[1], b[2], b[3], ident, ident))
    w("};")
    w("")

    # ── song_select reader ─────────────────────────────────────────────────
    w("/* ── song_select reader (slot bitmap match + offset search) ── */")
    w("#define GP_SONG_COLS %d" % song_cfg.cols)
    w("#define GP_SONG_ROWS %d" % song_cfg.rows)
    w("#define GP_SONG_LEN %d" % song_len)
    w("#define GP_N_SONGS %d" % len(catalog.templates))
    w("#define GP_SETLIST_MAIN 0")
    w("#define GP_SETLIST_BONUS 1")
    w("#define GP_SONG_ROI_SLOT 0")
    w("#define GP_SONG_ROI_FIRST 1")
    for nm, roi in (("SLOT", SONG_SLOT_ROI), ("FIRST", SONG_FIRST_ROI), ("BG", SETLIST_BG_ROI)):
        w("#define GP_SONG_%s_ROI {%d,%d,%d,%d}" % (nm, *roi))
    w("static const float gp_setlist_warmth_threshold = %.6gf;"
      % catalog.setlist_warmth_threshold)
    w("static const int16_t gp_song_dx[%d] = {%s};"
      % (len(song_cfg.dx_search), ",".join(str(d) for d in song_cfg.dx_search)))
    w("static const int16_t gp_song_dy[%d] = {%s};"
      % (len(song_cfg.dy_search), ",".join(str(d) for d in song_cfg.dy_search)))
    w("#define GP_SONG_NDX %d" % len(song_cfg.dx_search))
    w("#define GP_SONG_NDY %d" % len(song_cfg.dy_search))
    w("")
    for i, t in enumerate(catalog.templates):
        w("static const float gp_song_vec_%d[GP_SONG_LEN] = {%s};" % (i, _floats(t.vec)))
    w("")
    w("typedef struct {")
    w("  uint8_t setlist;      /* GP_SETLIST_* */")
    w("  uint8_t index;        /* song ordinal within its setlist */")
    w("  uint8_t roi_kind;     /* GP_SONG_ROI_* */")
    w("  const char *song_id;")
    w("  const float *vec;     /* GP_SONG_LEN */")
    w("} gp_song_template_t;")
    w("static const gp_song_template_t gp_song_templates[GP_N_SONGS] = {")
    for i, t in enumerate(catalog.templates):
        setlist = "GP_SETLIST_BONUS" if t.setlist == "bonus" else "GP_SETLIST_MAIN"
        roi = "GP_SONG_ROI_FIRST" if t.roi_kind == FIRST else "GP_SONG_ROI_SLOT"
        w('  {%s, %d, %s, "%s", gp_song_vec_%d},'
          % (setlist, t.index, roi, t.song_id, i))
    w("};")
    w("")

    # ── in-song score reader ───────────────────────────────────────────────
    w("/* ── in-song score reader (gap-segment + per-cell ink-coverage mask, L1) ── */")
    scfg = DEFAULT_SCORE_CONFIG
    score_len = scfg.glyph_rows * scfg.glyph_cols
    # Per-mode catalogs (only modes with a labelled corpus are emitted).
    score_samples = load_score_corpus()
    mode_cats = [(m, build_score_catalog(score_samples, mode=m)) for m in _SCORE_MODES]
    mode_cats = [(m, c) for m, c in mode_cats if c.templates]
    bands = [SCORE_DIGIT_BAND[m] for m, _ in mode_cats]
    max_bw = max((b[2] - b[0]) for b in bands) if bands else 0
    max_bh = max((b[3] - b[1]) for b in bands) if bands else 0

    w("#define GP_SCORE_GLYPH_ROWS %d" % scfg.glyph_rows)
    w("#define GP_SCORE_GLYPH_COLS %d" % scfg.glyph_cols)
    w("#define GP_SCORE_LEN %d" % score_len)
    w("#define GP_SCORE_NDIGITS 10          /* templates 0-9; row index == digit */")
    w("#define GP_SCORE_INK_FRAC %.6gf" % scfg.ink_frac)
    w("#define GP_SCORE_MIN_GAP %d" % scfg.min_gap)
    w("#define GP_SCORE_MIN_WIDTH %d" % scfg.min_width)
    w("#define GP_SCORE_MIN_INK %d" % scfg.min_ink)
    w("#define GP_SCORE_MAX_DIGITS 8        /* scratch bound; scores are <= 6 digits */")
    w("#define GP_SCORE_BAND_MAX_W %d" % max_bw)
    w("#define GP_SCORE_BAND_MAX_H %d" % max_bh)
    for i, (m, _c) in enumerate(mode_cats):
        w("#define GP_SCORE_MODE_%s %d" % (_c_ident(m).upper(), i))
    w("#define GP_N_SCORE_MODES %d" % len(mode_cats))
    w("")
    # Per-mode uint8 template array: row d = digit d's mean ink-coverage mask.
    for m, cat in mode_cats:
        by_digit = {t.digit: t.vec for t in cat.templates}
        rows = np.stack([by_digit[d] for d in range(10)])  # requires all 0-9 present
        w("static const uint8_t gp_score_%s_tmpl[GP_SCORE_NDIGITS][GP_SCORE_LEN] = {"
          % _c_ident(m))
        w(_u8_rows(rows))
        w("};")
    w("")
    w("typedef struct {")
    w("  uint16_t band[4];                          /* x0, y0, x1, y1 (canonical space) */")
    w("  const uint8_t (*tmpl)[GP_SCORE_LEN];       /* [10] per-digit coverage masks */")
    w("} gp_score_mode_t;")
    w("static const gp_score_mode_t gp_score_modes[GP_N_SCORE_MODES] = {")
    for m, _cat in mode_cats:
        b = SCORE_DIGIT_BAND[m]
        w("  {{%d,%d,%d,%d}, gp_score_%s_tmpl}," % (b[0], b[1], b[2], b[3], _c_ident(m)))
    w("};")
    w("")

    # ── score multiplier (colour-count classifier) ─────────────────────────
    w("/* ── score multiplier (colour of the medallion glyph: 2x gold/3x green/4x purple) ── */")
    w("#define GP_MULT_ROI {%d,%d,%d,%d}" % SCORE_MULT_ROI)
    w("#define GP_MULT_BRIGHT_MIN %d" % SCORE_MULT_BRIGHT_MIN)
    w("#define GP_MULT_SAT_MIN %d" % SCORE_MULT_SAT_MIN)
    w("#define GP_MULT_MIN_COUNT %d  /* fewer than this of the winning colour => 1x */"
      % SCORE_MULT_MIN_COUNT)
    w("")

    # ── note-streak counter (odometer OCR: dual-polarity per-cell coverage, L1) ──
    w("/* ── note-streak counter (3-tumbler odometer; per-cell coverage L1, 2 banks) ── */")
    tcfg = DEFAULT_STREAK_CONFIG
    streak_len = tcfg.glyph_rows * tcfg.glyph_cols
    tcat = build_streak_catalog(load_streak_corpus())
    max_cw = max(roi[2] - roi[0] for roi, _light in STREAK_CELLS)
    max_ch = max(roi[3] - roi[1] for roi, _light in STREAK_CELLS)
    w("#define GP_STREAK_GLYPH_ROWS %d" % tcfg.glyph_rows)
    w("#define GP_STREAK_GLYPH_COLS %d" % tcfg.glyph_cols)
    w("#define GP_STREAK_LEN %d" % streak_len)
    w("#define GP_STREAK_NDIGITS 10        /* templates 0-9 per bank; row index == digit */")
    w("#define GP_STREAK_NCELLS %d          /* hundreds, tens, units */" % len(STREAK_CELLS))
    w("#define GP_STREAK_INK_FRAC %.6gf" % tcfg.ink_frac)
    w("#define GP_STREAK_CELL_MAX_W %d" % max(max_cw, STREAK_NOTE_CELL[2] - STREAK_NOTE_CELL[0]))
    w("#define GP_STREAK_CELL_MAX_H %d" % max(max_ch, STREAK_NOTE_CELL[3] - STREAK_NOTE_CELL[1]))
    w("#define GP_STREAK_NOTE_ROI {%d,%d,%d,%d}  /* gold note-icon locked-position fiducial */"
      % STREAK_NOTE_CELL)
    w("#define GP_STREAK_NOTE_MAX_SAD %d  /* note-icon coverage L1 below this => locked (present) */"
      % STREAK_NOTE_MAX_SAD)
    w("#define GP_STREAK_UNK_DIST %d       /* best L1 above this => wheel unreadable */" % STREAK_UNK_DIST)
    w("#define GP_STREAK_UNK_MARGIN %d     /* runner-up gap below this => wheel unreadable */" % STREAK_UNK_MARGIN)
    w("#define GP_STREAK_DEBOUNCE {%d,%d,%d}  /* consecutive reads to commit a change [h,t,u] */"
      % STREAK_DEBOUNCE)
    w("#define GP_STREAK_MAX_STEP %d      /* reject a committed value jump larger than this (implausible) */"
      % STREAK_MAX_STEP)
    w("#define GP_STREAK_BANK_WD 0         /* white-on-dark bank (hundreds, tens) */")
    w("#define GP_STREAK_BANK_DL 1         /* dark-on-light bank (units wheel) */")
    w("")
    # Note-icon coverage template (locked-position fiducial) + the two per-polarity
    # uint8 digit banks: row d = digit d's mean coverage mask.
    w("static const uint8_t gp_streak_note_tmpl[GP_STREAK_LEN] = {%s};"
      % ",".join(str(int(v)) for v in tcat.note_tmpl))
    for nm, bank in (("wd", tcat.tmpl_wd), ("dl", tcat.tmpl_dl)):
        w("static const uint8_t gp_streak_tmpl_%s[GP_STREAK_NDIGITS][GP_STREAK_LEN] = {" % nm)
        w(_u8_rows(np.stack(bank)))
        w("};")
    w("")
    w("typedef struct {")
    w("  uint16_t roi[4];   /* x0, y0, x1, y1 (canonical space) */")
    w("  uint8_t  is_light; /* 1 = dark-digit-on-light wheel (units); 0 = white-on-dark */")
    w("  uint8_t  bank;     /* GP_STREAK_BANK_* */")
    w("} gp_streak_cell_t;")
    w("static const gp_streak_cell_t gp_streak_cells[GP_STREAK_NCELLS] = {")
    for roi, light in STREAK_CELLS:
        bank = "GP_STREAK_BANK_DL" if light else "GP_STREAK_BANK_WD"
        w("  {{%d,%d,%d,%d}, %d, %s}," % (roi[0], roi[1], roi[2], roi[3], int(light), bank))
    w("};")
    w("")

    w("#endif /* GAMEPLAY_METADATA_H */")
    return "\n".join(L) + "\n"
